// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE97ruxfKABxRu4hUSf8ASTB5nBcPspqE',
    appId: '1:221825579818:web:1b3191b7b7959357de7c53',
    messagingSenderId: '221825579818',
    projectId: 'tm-app-c01e7',
    authDomain: 'tm-app-c01e7.firebaseapp.com',
    storageBucket: 'tm-app-c01e7.appspot.com',
    measurementId: 'G-QE1L792NJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Xhu0sTREgGShWpMUdZ91EKDuqDar8BA',
    appId: '1:221825579818:android:52ffbeefef86cd33de7c53',
    messagingSenderId: '221825579818',
    projectId: 'tm-app-c01e7',
    storageBucket: 'tm-app-c01e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrebPR2YtQdhyKR0Nqi9MH0jTvY097U2g',
    appId: '1:221825579818:ios:37db4ac5f5d7d2e4de7c53',
    messagingSenderId: '221825579818',
    projectId: 'tm-app-c01e7',
    storageBucket: 'tm-app-c01e7.appspot.com',
    androidClientId: '221825579818-4s0qc18c2j8d5dk740qn82t0g3cgpvv8.apps.googleusercontent.com',
    iosClientId: '221825579818-3dc5hluhu5ahfj3vens7f8409aaiqdl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrebPR2YtQdhyKR0Nqi9MH0jTvY097U2g',
    appId: '1:221825579818:ios:37db4ac5f5d7d2e4de7c53',
    messagingSenderId: '221825579818',
    projectId: 'tm-app-c01e7',
    storageBucket: 'tm-app-c01e7.appspot.com',
    androidClientId: '221825579818-4s0qc18c2j8d5dk740qn82t0g3cgpvv8.apps.googleusercontent.com',
    iosClientId: '221825579818-3dc5hluhu5ahfj3vens7f8409aaiqdl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmApp',
  );
}
